services:
  # FastAPI Backend Service
  - type: web
    name: veriframe-backend  # Change to your preferred name
    env: python
    # pythonVersion: 3.12  # Specify your Python version
    rootDir: backend/
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT  # Assumes app instance named 'app' in main.py
    envVars:  # Add these in Render dashboard for security; example placeholders
      - key: STARKNET_RPC
        value: "https://starknet-sepolia.public.blastapi.io/rpc/v0_8"
      - key: JOB_REGISTRY_CONTRACT_ADDRESS
        value: "0x03465f9dd6f9b94daf51baacbcf1eeab963d987b24286934e3c23a1b75c9e8da"  # From your .env
      - key: STARKNET_NETWORK
        value: "sepolia"  # Example; adjust as needed
      - key: ENV # Example environment variable
        value: "development"  # or "production" 
      - key: DATABASE_URL
        fromDatabase:
          name: veriframe-db  # If using Render's Postgres
          property: connectionString
      - key: JOB_REGISTRY_ADDRESS
        value: "0x03103f3d37047b8bd0680c22a9b8d9502d5d1e34ab12259659dea2f6354ad7e8"  # From your .env
    buildFilter:
      paths:
        - 'backend/**/*.py'
        - 'backend/requirements.txt'
      ignoredPaths:
        - 'backend/tests/**'  # Optional: Ignore tests

  # Next.js Frontend Service
  - type: web
    name: veriframe-frontend  # Change to your preferred name
    env: node
    # nodeVersion: '22.15.1'
    rootDir: frontend/
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_STARKNET_RPC
        value: https://starknet-sepolia.public.blastapi.io/rpc/v0_8  # Points to your Starknet RPC
      - key: NEXT_PUBLIC_JOB_REGISTRY_CONTRACT_ADDRESS
        value: 0x03465f9dd6f9b94daf51baacbcf1eeab963d987b24286934e3c23a1b75c9e8da
      - key: NEXT_PUBLIC_API_URL
        value: https://veriframe-backend.onrender.com  # Points to your backend URL
      - key: NEXT_PUBLIC_STARKNET_NETWORK
        value: sepolia  # Example; adjust as needed
    buildFilter:
      paths:
        - 'frontend/**/*.js'
        - 'frontend/**/*.ts'
        - 'frontend/**/*.tsx'
        - 'frontend/package.json'
      ignoredPaths:
        - 'frontend/tests/**'  # Optional: Ignore tests